import AppKit

@MainActor
struct PasteboardSnapshot {
    private let items: [[NSPasteboard.PasteboardType: Data]]

    var containsSensitiveData: Bool {
        items.contains(where: { item in
            item.keys.contains(where: Self.sensitiveTypes.contains)
        })
    }

    init(pasteboard: NSPasteboard = .general) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            Dictionary(uniqueKeysWithValues: item.types.map { type in
                (type, item.data(forType: type) ?? Data())
            })
        }
    }

    // Safe spoken-fallback text from the moment the snapshot was taken, so a
    // clipboard manager writing during the Command-C wait is never read.
    var plainText: String? {
        guard !containsSensitiveData else { return nil }
        for item in items {
            guard
                let data = item[.string],
                let text = String(data: data, encoding: .utf8),
                !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            else { continue }
            return text
        }
        return nil
    }

    func restore(to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }

        let restoredItems = items.map { values in
            let item = NSPasteboardItem()
            for (type, data) in values {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(restoredItems)
    }

    private static let sensitiveTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.apple.is-sensitive"),
    ]
}
